Repository DearDreamTeam/deardream-backend, pull requests merged in 2025-06, with the labels that each got.

#11 [REVERT] 다음 내용을 병합 취소합니다. -> "[FIX] 카카오 소셜 로그인 -> 프론트엔드로 토큰 리다이렉트 코드 추가"
  src/main/java/com/deardream/deardream_be/domain/auth/controller/AuthController.java
Labels: ⚠️REVERT

#12 게시글 List 보기
  build.gradle
  src/main/java/com/deardream/deardream_be/domain/archive/MonthlyArchive.java
  src/main/java/com/deardream/deardream_be/domain/family/Family.java
  src/main/java/com/deardream/deardream_be/domain/family/Recipient.java
  src/main/java/com/deardream/deardream_be/domain/payment/Payment.java
  src/main/java/com/deardream/deardream_be/domain/post/Post.java
  src/main/java/com/deardream/deardream_be/domain/post/controller/PostController.java
  src/main/java/com/deardream/deardream_be/domain/post/dto/PostRequestDto.java
  src/main/java/com/deardream/deardream_be/domain/post/dto/PostResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/post/dto/PostUpdateDto.java
  src/main/java/com/deardream/deardream_be/domain/post/service/PostService.java
  src/main/java/com/deardream/deardream_be/domain/user/entity/User.java
  src/main/java/com/deardream/deardream_be/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/deardream/deardream_be/global/common/BaseEntity.java
Labels: ✨ FEAT

#13 [FIX] 카카오 로그인 profileImage + name(실명) 필드 추가 및 리팩토링 / 토큰 발급 로직 수정
  src/main/java/com/deardream/deardream_be/domain/auth/controller/AuthController.java
  src/main/java/com/deardream/deardream_be/domain/auth/dto/KakaoDTO.java
  src/main/java/com/deardream/deardream_be/domain/auth/dto/KakaoDto.java
  src/main/java/com/deardream/deardream_be/domain/auth/dto/KakaoLoginResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/auth/service/AuthServiceImplementation.java
  src/main/java/com/deardream/deardream_be/domain/auth/util/KakaoUtil.java
  src/main/java/com/deardream/deardream_be/domain/jwt/JwtAuthenticationFilter.java
  src/main/java/com/deardream/deardream_be/domain/jwt/JwtUtil.java
  src/main/java/com/deardream/deardream_be/global/config/SecurityConfig.java
Labels: 🐛 FIX, 🎨 REFACTOR
