Repository DearDreamTeam/deardream-backend, pull requests merged in 2025-08, with the labels that each got.

#149 [FIX] [수신자 -> 가족생성 -> 결제] 로 변경된 플로우에 맞게 코드 수정
  src/main/java/com/deardream/deardream_be/domain/family/entity/Family.java
  src/main/java/com/deardream/deardream_be/domain/family/service/FamilyServiceImplementation.java
  src/main/java/com/deardream/deardream_be/domain/payment/service/PaymentService.java
  src/main/java/com/deardream/deardream_be/domain/recipient/entity/Recipient.java
  src/main/java/com/deardream/deardream_be/global/apiPayload/code/status/ErrorStatus.java
Labels: 🐛 FIX

#151 fix: 어드민 기능 수정
  src/main/java/com/deardream/deardream_be/domain/archive/controller/AdminArchiveController.java
  src/main/java/com/deardream/deardream_be/domain/archive/repository/ArchiveRepository.java
  src/main/java/com/deardream/deardream_be/domain/archive/service/ArchiveService.java
  src/main/java/com/deardream/deardream_be/domain/institution/Institution.java
  src/main/java/com/deardream/deardream_be/domain/institution/controller/AdminInstitutionController.java
  src/main/java/com/deardream/deardream_be/domain/institution/dto/DeleteUsersRequestDto.java
  src/main/java/com/deardream/deardream_be/domain/institution/service/AdminInstitutionService.java
  src/main/resources/application-prod.yml
Labels: ✨ FEAT, 🐛 FIX

#152 fix: 탈퇴 관련 로직
  src/main/java/com/deardream/deardream_be/domain/user/service/UserServiceWithdrawImplementation.java
Labels: 🐛 FIX

#158 [REFACTOR] 이미지 예외처리 413, 415 상태코드 반영
  src/main/java/com/deardream/deardream_be/domain/recipient/service/RecipientServiceImplementation.java
  src/main/java/com/deardream/deardream_be/domain/user/service/UserServiceImplementation.java
  src/main/java/com/deardream/deardream_be/global/apiPayload/code/status/ErrorStatus.java
Labels: 🎨 REFACTOR

#166 [FIX] 탈퇴한 대표자의 남은 사용자의 relation/otherRelation 값 null값 처리
  src/main/java/com/deardream/deardream_be/domain/user/entity/User.java
  src/main/java/com/deardream/deardream_be/domain/user/service/UserServiceWithdrawImplementation.java
Labels: 🐛 FIX
