Repository DearDreamTeam/deardream-backend, pull requests merged in 2025-07, with the labels that each got.

#26 [REFACTOR] 사용하지 않는 entity 삭제 / Role에 ADMIN 추가
  src/main/java/com/deardream/deardream_be/domain/family/Recipient.java
  src/main/java/com/deardream/deardream_be/domain/user/Role.java
Labels: 🎨 REFACTOR

#28 [FIX] [FEAT] [REFACTOR] user patch api 오류 수정 / dto 추가 / 토큰 필드 꺼내는 방식 리팩토링
  src/main/java/com/deardream/deardream_be/domain/user/controller/UserController.java
  src/main/java/com/deardream/deardream_be/domain/user/dto/UserRequestDto.java
  src/main/java/com/deardream/deardream_be/domain/user/dto/UserResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/user/dto/UserUpdateDto.java
  src/main/java/com/deardream/deardream_be/domain/user/entity/User.java
  src/main/java/com/deardream/deardream_be/domain/user/service/UserService.java
  src/main/java/com/deardream/deardream_be/domain/user/service/UserServiceImplementation.java
Labels: ✨ FEAT, 🐛 FIX, 🎨 REFACTOR

#42 Revert "[FIX] name -> nickname 필드로 수정"
  src/main/java/com/deardream/deardream_be/domain/auth/controller/AuthController.java
  src/main/java/com/deardream/deardream_be/domain/auth/dto/KakaoDto.java
  src/main/java/com/deardream/deardream_be/domain/auth/dto/KakaoLoginResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/auth/service/AuthService.java
  src/main/java/com/deardream/deardream_be/domain/auth/service/AuthServiceImplementation.java
  src/main/java/com/deardream/deardream_be/domain/auth/util/KakaoUtil.java
  src/main/java/com/deardream/deardream_be/domain/family/Family.java
  src/main/java/com/deardream/deardream_be/domain/family/FamilyRepository.java
  src/main/java/com/deardream/deardream_be/domain/family/controller/FamilyController.java
  src/main/java/com/deardream/deardream_be/domain/family/dto/FamilyMembersResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/family/dto/FamilyRequestDto.java
  src/main/java/com/deardream/deardream_be/domain/family/dto/FamilyResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/family/entity/Family.java
  src/main/java/com/deardream/deardream_be/domain/family/repository/FamilyRepository.java
  src/main/java/com/deardream/deardream_be/domain/family/service/FamilyService.java
  src/main/java/com/deardream/deardream_be/domain/family/service/FamilyServiceImplementation.java
  src/main/java/com/deardream/deardream_be/domain/jwt/JwtAuthenticationFilter.java
  src/main/java/com/deardream/deardream_be/domain/jwt/JwtUtil.java
  src/main/java/com/deardream/deardream_be/domain/user/Role.java
  src/main/java/com/deardream/deardream_be/domain/user/controller/UserController.java
  src/main/java/com/deardream/deardream_be/domain/user/dto/RegisterResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/user/dto/UserRequestDto.java
  src/main/java/com/deardream/deardream_be/domain/user/dto/UserResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/user/dto/UserUpdateDto.java
  src/main/java/com/deardream/deardream_be/domain/user/entity/User.java
  src/main/java/com/deardream/deardream_be/domain/user/repository/UserRepository.java
  src/main/java/com/deardream/deardream_be/domain/user/service/UserService.java
  src/main/java/com/deardream/deardream_be/domain/user/service/UserServiceImplementation.java
  src/main/java/com/deardream/deardream_be/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/deardream/deardream_be/global/config/SecurityConfig.java
Labels: ⚠️REVERT

#48 [FEAT] 유저 프로필 사진 등록, 수정, 삭제 기능 추가
  src/main/java/com/deardream/deardream_be/domain/user/controller/UserController.java
  src/main/java/com/deardream/deardream_be/domain/user/dto/UserRequestDto.java
  src/main/java/com/deardream/deardream_be/domain/user/dto/UserResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/user/entity/User.java
  src/main/java/com/deardream/deardream_be/domain/user/service/UserService.java
  src/main/java/com/deardream/deardream_be/domain/user/service/UserServiceImplementation.java
Labels: ✨ FEAT

#49 [FIX] 유저 엔티티에서 필드 이름 변경 profileImageUrl -> profileImage
  src/main/java/com/deardream/deardream_be/domain/user/dto/UserResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/user/entity/User.java
Labels: 🐛 FIX

#53 [FIX] 이미지 url 저장 형식 변경 / 가족 ENUM값 수정
  src/main/java/com/deardream/deardream_be/domain/user/Relation.java
  src/main/java/com/deardream/deardream_be/domain/user/service/UserServiceImplementation.java
Labels: 🐛 FIX

#59 [FIX] familyLink 로직 수정
  src/main/java/com/deardream/deardream_be/domain/family/controller/FamilyController.java
  src/main/java/com/deardream/deardream_be/domain/family/service/FamilyServiceImplementation.java
  src/main/java/com/deardream/deardream_be/domain/jwt/JwtAuthenticationFilter.java
  src/main/java/com/deardream/deardream_be/domain/jwt/JwtUtil.java
  src/main/java/com/deardream/deardream_be/domain/user/entity/User.java
  src/main/java/com/deardream/deardream_be/global/config/SecurityConfig.java
Labels: 🐛 FIX

#62 fix post는 한 달에 최대 20개만 작성 가능합니다. #56
  src/main/java/com/deardream/deardream_be/domain/post/controller/PostController.java
  src/main/java/com/deardream/deardream_be/domain/post/dto/CreatePostResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/post/dto/UpdateResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/post/repository/PostRepository.java
  src/main/java/com/deardream/deardream_be/domain/post/service/PostService.java
Labels: ✨ FEAT, 🐛 FIX

#68 fix: ArchiveListResponse 직렬화 오류 해결 #10
  src/main/java/com/deardream/deardream_be/domain/archive/dto/ArchiveListResponse.java
Labels: 🐛 FIX

#78 fix: patch update post
  src/main/java/com/deardream/deardream_be/domain/post/controller/PostController.java
  src/main/java/com/deardream/deardream_be/domain/post/dto/PatchPostDto.java
  src/main/java/com/deardream/deardream_be/domain/post/service/PostService.java
Labels: 🐛 FIX

#82 fix: thumbnail 추가
  src/main/java/com/deardream/deardream_be/domain/archive/dto/ArchiveResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/archive/service/ArchiveService.java
  src/main/java/com/deardream/deardream_be/domain/post/service/PostImageService.java
  src/main/java/com/deardream/deardream_be/domain/post/service/PostService.java
  src/main/resources/application-prod.yml
Labels: 🐛 FIX

#83 [FEAT] [FIX] 가족 초대장, 가족 초대 링크 생성 관련 로직 수정
  src/main/java/com/deardream/deardream_be/domain/family/controller/FamilyController.java
  src/main/java/com/deardream/deardream_be/domain/family/dto/FamilyInvitationDto.java
  src/main/java/com/deardream/deardream_be/domain/family/dto/FamilyMembersResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/family/service/FamilyService.java
  src/main/java/com/deardream/deardream_be/domain/family/service/FamilyServiceImplementation.java
  src/main/java/com/deardream/deardream_be/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/deardream/deardream_be/global/config/SecurityConfig.java
Labels: ✨ FEAT, 🐛 FIX

#86 [FEAT] 카카오 로그아웃 기능 추가
  src/main/java/com/deardream/deardream_be/domain/auth/controller/AuthController.java
  src/main/java/com/deardream/deardream_be/domain/auth/service/AuthService.java
  src/main/java/com/deardream/deardream_be/domain/auth/service/AuthServiceImplementation.java
  src/main/java/com/deardream/deardream_be/domain/auth/util/KakaoUtil.java
  src/main/java/com/deardream/deardream_be/global/config/RestTemplateConfig.java
  src/main/java/com/deardream/deardream_be/global/config/SecurityConfig.java
  src/main/resources/application-prod.yml
Labels: ✨ FEAT, 🎨 REFACTOR

#87 fix: 마스터 어드민 관련 api 수정
  src/main/java/com/deardream/deardream_be/domain/archive/controller/AdminArchiveController.java
  src/main/java/com/deardream/deardream_be/domain/archive/controller/ArchiveController.java
  src/main/java/com/deardream/deardream_be/domain/archive/converter/ArchiveConverter.java
  src/main/java/com/deardream/deardream_be/domain/archive/dto/AdminArchive.java
  src/main/java/com/deardream/deardream_be/domain/archive/dto/AdminArchiveRequest.java
  src/main/java/com/deardream/deardream_be/domain/archive/dto/AdminHomeArchiveResponse.java
  src/main/java/com/deardream/deardream_be/domain/archive/dto/AdminInstitutionArchiveResponse.java
  src/main/java/com/deardream/deardream_be/domain/archive/repository/ArchiveRepository.java
  src/main/java/com/deardream/deardream_be/domain/archive/service/ArchiveScheduler.java
  src/main/java/com/deardream/deardream_be/domain/archive/service/ArchiveService.java
  src/main/java/com/deardream/deardream_be/domain/archive/service/PdfRender.java
  src/main/java/com/deardream/deardream_be/domain/institution/dto/CreateInstitutionDto.java
  src/main/java/com/deardream/deardream_be/domain/payment/Payment.java
  src/main/java/com/deardream/deardream_be/domain/payment/controller/SubscriptionScheduler.java
  src/main/java/com/deardream/deardream_be/domain/payment/service/PaymentService.java
  src/main/java/com/deardream/deardream_be/domain/post/service/PostService.java
  src/main/java/com/deardream/deardream_be/global/config/SecurityConfig.java
Labels: 🐛 FIX

#103 feat: 플랜 해지, 가족 삭제(테스트), 현재 플랜 상태
  src/main/java/com/deardream/deardream_be/domain/archive/entity/ArchiveBookmark.java
  src/main/java/com/deardream/deardream_be/domain/family/controller/FamilyController.java
  src/main/java/com/deardream/deardream_be/domain/family/service/FamilyService.java
  src/main/java/com/deardream/deardream_be/domain/family/service/FamilyServiceImplementation.java
  src/main/java/com/deardream/deardream_be/domain/payment/Payment.java
  src/main/java/com/deardream/deardream_be/domain/payment/controller/PaymentController.java
  src/main/java/com/deardream/deardream_be/domain/payment/service/PaymentService.java
  src/main/java/com/deardream/deardream_be/domain/post/Post.java
  src/main/java/com/deardream/deardream_be/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/deardream/deardream_be/global/config/SecurityConfig.java
  src/main/resources/application-prod.yml
Labels: ✨ FEAT

#104 [FEAT] 토큰 재발급 로직 추가
  src/main/java/com/deardream/deardream_be/domain/auth/controller/AuthController.java
  src/main/java/com/deardream/deardream_be/domain/auth/service/AuthService.java
  src/main/java/com/deardream/deardream_be/domain/auth/service/AuthServiceImplementation.java
Labels: ✨ FEAT

#105 [REFACTOR] whiteLabel redirectUri 추가
  src/main/java/com/deardream/deardream_be/domain/auth/util/WhiteRedirectUriList.java
Labels: 🎨 REFACTOR, ✅ TEST

#112 [FIX] family에 불리언 2개 값 추가 / recipient에 변수 타입 수정
  src/main/java/com/deardream/deardream_be/domain/family/entity/Family.java
  src/main/java/com/deardream/deardream_be/domain/recipient/dto/RecipientRequestDto.java
  src/main/java/com/deardream/deardream_be/domain/recipient/dto/RecipientResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/recipient/entity/Recipient.java
Labels: 🐛 FIX

#115 fix: 한국 시간 업데트
  src/main/java/com/deardream/deardream_be/domain/archive/dto/ArchiveListResponse.java
  src/main/java/com/deardream/deardream_be/domain/archive/dto/ArchiveResponseDto.java
  src/main/java/com/deardream/deardream_be/domain/archive/entity/MonthlyArchive.java
  src/main/java/com/deardream/deardream_be/domain/archive/repository/ArchiveRepository.java
  src/main/java/com/deardream/deardream_be/domain/archive/service/ArchiveService.java
  src/main/java/com/deardream/deardream_be/domain/archive/service/PdfRender.java
  src/main/java/com/deardream/deardream_be/domain/payment/controller/KakaoPayController.java
  src/main/java/com/deardream/deardream_be/domain/payment/service/KakaoPayService.java
  src/main/java/com/deardream/deardream_be/domain/payment/util/KakaoPayRedirectUriList.java
  src/main/java/com/deardream/deardream_be/domain/post/controller/PostController.java
  src/main/java/com/deardream/deardream_be/domain/post/service/PostService.java
  src/main/resources/application-prod.yml
Labels: 🐛 FIX

#117 [FEAT] 회원 탈퇴 로직 추가
  src/main/java/com/deardream/deardream_be/domain/archive/entity/MonthlyArchive.java
  src/main/java/com/deardream/deardream_be/domain/archive/repository/ArchiveRepository.java
  src/main/java/com/deardream/deardream_be/domain/family/entity/Family.java
  src/main/java/com/deardream/deardream_be/domain/post/repository/PostRepository.java
  src/main/java/com/deardream/deardream_be/domain/recipient/repository/RecipientRepository.java
  src/main/java/com/deardream/deardream_be/domain/user/controller/UserController.java
  src/main/java/com/deardream/deardream_be/domain/user/entity/User.java
  src/main/java/com/deardream/deardream_be/domain/user/repository/UserRepository.java
  src/main/java/com/deardream/deardream_be/domain/user/service/UserService.java
  src/main/java/com/deardream/deardream_be/domain/user/service/UserServiceWithdraw.java
  src/main/java/com/deardream/deardream_be/domain/user/service/UserServiceWithdrawImplementation.java
Labels: ✨ FEAT

#120 [FIX] 회원 탈퇴 api 이름 변경
  src/main/java/com/deardream/deardream_be/domain/user/controller/UserController.java
Labels: 🎨 REFACTOR

#130 [REFACTOR] 가족 생성 시 대표자의 relation/otherRelation 디폴트 값 들어가게 수정
  src/main/java/com/deardream/deardream_be/domain/family/service/FamilyServiceImplementation.java
  src/main/java/com/deardream/deardream_be/domain/user/entity/User.java
Labels: 🎨 REFACTOR

#131 [FIX] 회원 탈퇴 시 payment userId FK에 걸려서 탈퇴 안되면 문제 해결
  src/main/java/com/deardream/deardream_be/domain/user/service/UserServiceWithdrawImplementation.java
Labels: 🐛 FIX

#133 [FEAT] 유저 등록 시 userRequestDto에서 profileImage가 url로 올 경우 기능 추가
  src/main/java/com/deardream/deardream_be/domain/post/service/PostImageService.java
  src/main/java/com/deardream/deardream_be/domain/user/dto/UserRequestDto.java
  src/main/java/com/deardream/deardream_be/domain/user/service/UserServiceImplementation.java
  src/main/java/com/deardream/deardream_be/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ FEAT

#134 fix: 플랜 해지 - 가정/기관
  src/main/java/com/deardream/deardream_be/domain/family/entity/Family.java
  src/main/java/com/deardream/deardream_be/domain/family/service/FamilyServiceImplementation.java
  src/main/java/com/deardream/deardream_be/domain/payment/controller/PaymentController.java
  src/main/java/com/deardream/deardream_be/domain/payment/service/KakaoPayService.java
  src/main/java/com/deardream/deardream_be/domain/payment/service/PaymentService.java
  src/main/java/com/deardream/deardream_be/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ FEAT, 🐛 FIX

#141 fix: Archive 생성 시 썸네일 이미지 추가
  src/main/resources/static/images/default-profile.svg
  src/main/resources/static/images/logo.svg
  src/main/resources/static/images/ribbon.svg
  src/main/resources/templates/index.html
  src/main/resources/templates/style.css
Labels: 🐛 FIX
